[window]
opacity = 0.8

[font]
size = 12.0

normal = { family = "HackNerdFont" }

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_timeout = 0
blink_interval = 650
